//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public int CurrentKilometer { get; set; }
        public byte[] Image { get; set; }
        public bool IsProper { get; set; }
        public bool IsAvailable { get; set; }
        public string BranchExactLocation { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual carType carType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
    }
}
