//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public System.DateTime LocationStartDay { get; set; }
        public System.DateTime LocationEndDate { get; set; }
        public Nullable<System.DateTime> DateCarReturned { get; set; }
        public int UserId { get; set; }
        public int CarId { get; set; }
        public int Id { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual user user { get; set; }
    }
}
